main=Day15

all:
	javac *.java

clean:
	rm -rf *.class

test:
	java $(main) < 1.in
	java $(main) < 2.in
	java $(main) < 3.in
	java $(main) < 4.in
	java $(main) < 5.in
	java $(main) < 6.in
	java $(main) < 7.in
	java $(main) < 8.in
